// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhM8-VYmuK2slYqTptl8ij_OwLr-6eR7Y',
    appId: '1:211565996613:web:24abc64ccd18f8aecb112c',
    messagingSenderId: '211565996613',
    projectId: 'traverscore',
    authDomain: 'traverscore.firebaseapp.com',
    storageBucket: 'traverscore.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANs8lCrsxcGkk2tWNX-vE7vpOpTN3g7xY',
    appId: '1:211565996613:android:657b592317edd7bfcb112c',
    messagingSenderId: '211565996613',
    projectId: 'traverscore',
    storageBucket: 'traverscore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfhaIq-dKsIelxhgFz3Kt7b_5z3SOqFFs',
    appId: '1:211565996613:ios:fd76bd124d80bca0cb112c',
    messagingSenderId: '211565996613',
    projectId: 'traverscore',
    storageBucket: 'traverscore.firebasestorage.app',
    androidClientId: '211565996613-sinr57juugvkkuhgvgug45q4sca1d2nv.apps.googleusercontent.com',
    iosClientId: '211565996613-ei1icrlckl5fvu154i2ti6nfrkoshfmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.traversApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhM8-VYmuK2slYqTptl8ij_OwLr-6eR7Y',
    appId: '1:211565996613:web:9a439fa882d851a0cb112c',
    messagingSenderId: '211565996613',
    projectId: 'traverscore',
    authDomain: 'traverscore.firebaseapp.com',
    storageBucket: 'traverscore.firebasestorage.app',
  );

}